version: '3.7'
services:
    db:
        image: mysql:latest
        restart: always
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/database/data:/var/lib/mysql
        ports:
            - "3309:3306"
        networks:
            - nginx-php74-db
    php-fpm:
        build:
            context: ./docker/php-fpm
        container_name: php
        depends_on:
            - db
        volumes:
            - .:/var/www/salama
            - /etc/php/7.2/cli/php.ini:/usr/local/etc/php/php.ini
        environment:
            PHP_IDE_CONFIG: serverName=salama
            APP_ENV: ${APP_ENV}
            APP_SECRET: ${APP_SECRET}
            DATABASE_URL: 'mysql://${DATABASE_USER}:${DATABASE_ROOT_PASSWORD}@db:3306/${DATABASE_NAME}?serverVersion=5.7'
            CORS_ALLOW_ORIGIN: '${CORS_ALLOW_ORIGIN}'
            JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
            JWT_PUBLIC_KEY: '${JWT_PUBLIC_KEY}'
            JWT_PASSPHRASE: '${JWT_PASSPHRASE}'
            SYMFONY_ENV: ${APP_ENV}
        networks:
            - nginx-php74-db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: salama_phpmyadmin
        ports:
            - "9999:80"
        depends_on:
            -  db
        networks:
            - nginx-php74-db
    nginx:
        container_name: nginx
        build:
            context: ./docker/nginx
        volumes:
            - .:/var/www/salama
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/logs:/var/log
        depends_on:
            - php-fpm
        networks:
            - nginx-php74-db
        ports:
            - "8080:80"
        environment:
            XDEBUG_CONFIG: "remote_host=TODY-ASUS-GAMING idekey=PHPSTORM"

networks:
    nginx-php74-db: